const language = en; //available languages: english (en), hungarian (hu)
const numberOfPracticeBlocks = 2;
const numberOfBlocks = 25;
const numberOfBlockElements = 80;
const numberOfSequenceRepetitions = 10;
const patternTrialImage = "url(static/images/dalmata.jpg)";
const randomTrialImage = "url(static/images/dalmata.jpg)";
const rsi = 120;
const initialDelay = 1000;